### ISSUE TITLE
Match the ordering of parts in the file with the documentation

### ISSUE THREAD

**Issue by fulldecent** [twbs/examples#303] opened 2023-09-08 03:48 UTC
In the example here

functions are below the customizations

But in

https://getbootstrap.com/docs/5.3/customize/sass/

The functions are above the customizations. And it even gives a 1. 2. 3. order to make that seem significant.

**Comment by julien-deramond** [comment] 2023-09-08 05:17
For consistency, even if the examples are working, you're right @fulldecent, we should change the order (and the comments) in the following examples:
- color-modes
- parcel
- sass-js
- sass-js-esm
- vite
- vue
- webpack

PR is welcome :)

**Comment by julien-deramond** [comment] 2023-09-08 05:19
Duplicate of #40. Closing it.

**Closed by julien-deramond** 2023-09-08 05:19 UTC
